apply plugin: "com.android.application"
apply plugin: "org.jetbrains.kotlin.android"
apply plugin: "org.jetbrains.kotlin.kapt"
apply plugin: "org.jetbrains.kotlin.plugin.compose"

android {
    namespace "com.deadlinemate"
    compileSdk 35

    defaultConfig {
        applicationId "com.deadlinemate"
        minSdk 26
        targetSdk 35
        versionCode 6
        versionName "1.0.32"
        buildConfigField "String", "MIPUSH_APP_ID", "\"${project.findProperty("mipushAppId") ?: ""}\""
        buildConfigField "String", "MIPUSH_APP_KEY", "\"${project.findProperty("mipushAppKey") ?: ""}\""
    }

    buildFeatures {
        compose true
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    splits {
        abi {
            enable true
            reset()
            include "arm64-v8a", "x86_64"
            universalApk false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation "androidx.core:core-ktx:1.13.1"
    implementation "androidx.activity:activity-compose:1.10.1"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.9.2"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.2"
    implementation "androidx.lifecycle:lifecycle-runtime-compose:2.9.2"
    implementation "androidx.compose.ui:ui-android:1.7.0"
    implementation "androidx.compose.ui:ui-tooling-preview-android:1.7.0"
    implementation "androidx.compose.material3:material3-android:1.3.0"
    implementation "androidx.navigation:navigation-compose:2.7.7"
    implementation "androidx.room:room-runtime:2.6.0"
    implementation "androidx.room:room-ktx:2.6.0"
    implementation "androidx.security:security-crypto:1.1.0-alpha06"
    implementation "com.squareup.okhttp3:okhttp:4.12.0"
    implementation "com.google.mlkit:text-recognition:16.0.1"
    implementation "com.google.mlkit:text-recognition-chinese:16.0.1"
    implementation files("libs/MiPush_SDK_Client_7_9_2-C_3rd.aar")
    kapt "androidx.room:room-compiler:2.6.0"

    debugImplementation "androidx.compose.ui:ui-tooling-android:1.7.0"
}
